// <auto-generated />
namespace GitQuery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changeCurrentDB3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeCurrentDB3));
        
        string IMigrationMetadata.Id
        {
            get { return "201507021333052_changeCurrentDB3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
